### ISSUE TITLE
low map issue...

### ISSUE THREAD

**Issue by DeidaraYang** [adursun/wsddn.pytorch#21]
After getting 10th epoch model. The program evaluated this model and returned a series of results. But it seems that the results are very low...
![3c4e8a1ec68c927d3a1a4fdea0a0363](https://user-images.githubusercontent.com/52477062/102677740-af07c800-41de-11eb-8cd0-31e9047c1a88.jpg)

**Comment by adursun** [comment]
Hi, thank you for your interest.

Unfortunately, the training is not fully deterministic, so it might return low mAP sometimes. Can you please try re-training?

**Comment by DeidaraYang** [comment]
yeah I try again. This time I tested the 20th epoch model but the result still very low....
By the way, when I tested the model,  I still used trainval data cuz I felt that maybe the performance will be better rather than test dataset. 
![{2TRFROV)~I4%_QKMI@P69D](https://user-images.githubusercontent.com/52477062/102692638-9aafe380-424f-11eb-9a79-cc4cc3360d06.png)

**Comment by DeidaraYang** [comment]
And this is my training process. I don't know whether it's correct...
![I@5AK)~@~A75D ENMWM9CAX](https://user-images.githubusercontent.com/52477062/102692849-2e35e400-4251-11eb-87ef-d7344ebfb275.png)

**Comment by adursun** [comment]
Yes, your training output looks good.

Can you please download and put [this file](https://www.dropbox.com/s/xyi4hgms6y3ldmj/vgg_epoch_20.pt?dl=1) into `states` directory and run:

```bash
python src/evaluate.py --base_net vgg --state_path states/vgg_epoch_20.pt
```

Its output should be as follows:

```
Avg AP: [0.38831317 0.45263229 0.24562751 0.26572207 0.12294847 0.59961043
 0.47957328 0.24194355 0.09629139 0.29096157 0.15507882 0.26510262
 0.31636181 0.53462855 0.06115122 0.16652659 0.33271927 0.29181557
 0.47336772 0.51627529]
Avg mAP: 0.3148325589240723
```

**Comment by DeidaraYang** [comment]
thanks author! The results I run nearly same as the one that you give.
So... it looks strange and I think something wrong in training.
Maybe the number of epoch is too small?

**Comment by adursun** [comment]
You are welcome! The pretrained state file I've sent is a result of 20 epochs training, so I don't think epoch count is a problem.

On the other hand, the training might stuck at a local minimum. Can you please try with the following:

```bash
python src/train.py --base_net vgg --lr 1e-4
```

**Comment by DeidaraYang** [comment]
thanks author! it can work!

**Comment by adursun** [comment]
Thank you too!
