### ISSUE TITLE
how to use the method in my own dataset, and the dataset is  voc format

### ISSUE THREAD

**Issue by weihancug** [adursun/wsddn.pytorch#22]
Hello, if I want to use this algorithm in my own data, a remote sensing image dataset. How should I modify the codes. 
In addition, what algorithm should I choose to generate proposals and how to format the proposal files to match this detector.

Thank you very much for your reply.

**Comment by adursun** [comment]
Hello, thank you for your interest.

You can modify `src/datasets.py` to work with custom datasets. Some ideas coming to my mind:

1. Updating `CLASS2ID` with custom categories
2. Generating Edge Boxes for custom dataset using [1](https://stackoverflow.com/questions/54843550/edge-box-detection-using-opencv-python), [2](https://github.com/dculibrk/edge_boxes_with_python), [3](https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/samples/edgeboxes_demo.py) (I remember generating Edge Boxes with OpenCV)
3. Generating `.xml` annotation files in PASCAL VOC format

**Comment by weihancug** [comment]
Very thanks for your answer. @adursun

**Comment by kkhuang1997** [comment]
> Hello, thank you for your interest.
> 
> You can modify `src/datasets.py` to work with custom datasets. Some ideas coming to my mind:
> 
> 1. Updating `CLASS2ID` with custom categories
> 2. Generating Edge Boxes for custom dataset using [1](https://stackoverflow.com/questions/54843550/edge-box-detection-using-opencv-python), [2](https://github.com/dculibrk/edge_boxes_with_python), [3](https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/samples/edgeboxes_demo.py) (I remember generating Edge Boxes with OpenCV)
> 3. Generating `.xml` annotation files in PASCAL VOC format


Hello,  i have some problems about the second point.  When i browse your code, i found that the loaded .mat file has "boxScores".   And when i choose selective search algorithm to generate  proposals, it dosen't have this boxscore. Whether this boxscore is required，can it be omitted?
And how can i generate this boxscore with the selective search algorithm if necessary.

Thank you for your reply.

**Comment by adursun** [comment]
Hello,

If you don't have scores for proposals, you can set them to `1.0` to neutralize the effect.

**Comment by kkhuang1997** [comment]
> Hello,
> 
> If you don't have scores for proposals, you can set them to `1.0` to neutralize the effect.

Ok，thanks for your reply！

**Comment by JMcarrot** [comment]
Hello, for the second point, how to obtain .mat file for voc2012?

**Comment by adursun** [comment]
@JMcarrot You can generate edge boxes using OpenCV.
