### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'image'

### ISSUE THREAD

**Issue by Scienthusiasts** [adursun/wsddn.pytorch#33]
Hi！I'm trying to run train.py to train the network but I'm having this problem:
TypeError: __call__() got an unexpected keyword argument 'image'
and It seems that the problem is in this part of `utils.py`:
![image](https://github.com/adursun/wsddn.pytorch/assets/54543888/d2aadd89-bd2c-4413-ab5d-f7644b766e50)
how can I solve the problem，I'm not sure if it's the code or me, thank you!

**Comment by adursun** [comment]
Hi,

Please check the version of `albumentations` package in your local. This code expects `albumentations==0.4.3` as in the [requirements.txt](https://github.com/adursun/wsddn.pytorch/blob/master/requirements.txt#L10C1-L10C22).

**Comment by Scienthusiasts** [comment]
thanks for your reply！but I still got the problem below:

![image](https://github.com/adursun/wsddn.pytorch/assets/54543888/03c034b3-9b3f-4e2a-9c2f-6a731cb68462)

**Comment by adursun** [comment]
Please use the exact versions in https://github.com/adursun/wsddn.pytorch/blob/master/requirements.txt, the new package methods/parameters might cause problems.

**Comment by Scienthusiasts** [comment]
Oooh,I got, I have chaged the code ,I reverted the code back to the original and it worked：
![image](https://github.com/adursun/wsddn.pytorch/assets/54543888/71dcd763-cdb3-482e-b904-c0bf5626f5cb)
thanks a lot！

**Comment by Scienthusiasts** [comment]
Thank you for your patience！, but I still have a question, in the original paper the author used the SPP module, but it seem that your version doesn‘t use it？
